version: '3'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx_inception
    container_name: nginx
    init: true
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - ../data/wordpress:/var/www/html
    ports:
      - "443:443"
    restart: always

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb_inception
    container_name: mariadb
    init: true
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - ../data/mariadb:/var/lib/mysql
    restart: always

  # wordpress:
  #   build:
  #     context: requirements/wordpress
  #     dockerfile: Dockerfile
  #   image: wordpress_inception
  #   container_name: wordpress
  #   init: true
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #   expose:
  #     - "9000"
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - ../data/wordpress:/var/www/html
  #   restart: always

networks:
  inception:
    driver: bridge

# volumes:
#   wordpress:
#     # name: wordpress_volume
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /Users/jergashe/Documents/projects/all_inception/docker-compose/data/wordpress
  
#   mariadb:
#     # name: mariadb_volume
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: /Users/jergashe/Documents/projects/all_inception/docker-compose/data/mariadb

